apiVersion: v1
kind: Service
metadata:
  namespace: dubbogo
  name: dubbogo-nacos
  labels:
    app: dubbogo-nacos
spec:
  ports:
    - port: 8848
      name: nacos
      targetPort: 8848
  clusterIP: None
  selector:
    app: dubbogo-nacos

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbogo-nacos
  namespace: dubbogo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbogo-nacos
  template:
    metadata:
      labels:
        app: dubbogo-nacos
        dubbogo-registry: nacos
    spec:
      containers:
        - image: nacos/nacos-server:1.2.0
          name: server
          ports:
          - name: nacos
            containerPort: 8848
            protocol: TCP
          env:
          - name: PREFER_HOST_MODE
            value: hostname
          - name: MODE
            value: standalone