name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: "*"

jobs:
  build:
    name: ${{ matrix.os }} - Go ${{ matrix.go_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      # If you want to matrix build , you can append the following list.
      matrix:
        go_version:
          - 1.17
        os:
          - ubuntu-latest
    steps:
    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        # Cache
        path: ~/go/pkg/mod
        # Cache key
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Get dependencies
      run: |
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        else
            go get -v -t -d ./...
        fi
    - name: Install imports-formatter
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        export GO111MODULE=on
        cd ~
        go get -u github.com/dubbogo/tools/cmd/imports-formatter@v1.0.7
    - name: Check improts
      run: |
        imports-formatter -path .
        git status && [[ -z `git status -s` ]]
    - name: gofmt
      run: |
        go fmt ./... && git status && [[ -z `git status -s` ]]
        # diff -u <(echo -n) <(gofmt -d -s .)
    - name: Verify
      run: |
        make verify
    # This step only runs when the event type is a pull_request
    - name: Integrate Test
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        chmod +x integrate_test.sh && [[ -n "${{github.event.pull_request.head.repo.full_name}}" ]] && [[ -n "${{github.event.pull_request.head.sha}}" ]] && [[ -n "${{github.base_ref}}" ]] && ./integrate_test.sh ${{github.event.pull_request.head.repo.full_name}} ${{github.event.pull_request.head.sha}} ${{github.base_ref}}